# Use root/example as user/password credentials
version: '3.1'


services:
  redis:
    image: redis
    restart: "no"
    container_name: redis
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
